-- ===========================================================================
-- Phase 1 — services catalogue + booking_requests extension
-- APPLIED to project mirabelle-b-booking (dqglhppksyhekaflnyop) 2026-08-26
-- ===========================================================================
--
-- Applied as five migrations in this order:
--   phase1_services_table
--   phase1_seed_services
--   phase1_extend_booking_requests
--   phase1_status_vocabulary
--   phase1_appointments_view
--
-- ADDITIVE. Nothing was dropped or renamed. booking_requests keeps its name
-- and every existing column, so the deployed site, the after-insert trigger
-- (notify_trigger.sql) and the notify-booking function all kept working
-- through the migration without a redeploy. Verified after applying:
--   - all 3 existing rows intact
--   - anon SELECT on booking_requests returns []
--   - anon SELECT on the new appointments view returns []
--   - anon INSERT still returns 201
--
-- The full statements are recorded in the Supabase migration history. This
-- file documents the decisions behind them.
--
-- ---------------------------------------------------------------------------
-- services
-- ---------------------------------------------------------------------------
-- anon may SELECT where active=true, because name/price/duration are already
-- printed on the public site. No write policy: seeding is service_role only.
--
-- starting_price is NULL for the five styles the site publishes no figure for
-- (Fulani, Kids', Braided Updo, Half Up Half Down, Goddess). The form must
-- keep saying "Price agreed when you book" for those. DO NOT populate these
-- with an estimate — a published price the salon has not agreed to is the
-- same class of problem as the testimonials removed on 2026-08-26.
--
-- 13 rows seeded: the 9 work-card styles plus loc maintenance, starter locs,
-- custom wig and sew-in, all of which appear in the site's price table.
--
-- ---------------------------------------------------------------------------
-- booking_requests, new columns
-- ---------------------------------------------------------------------------
--   service_id                     -> services(id), nullable; the live site
--                                     still posts free-text `style`
--   appointment_date/_time         the slot the SALON agrees, kept separate
--                                  from preferred_date/preferred_time so a
--                                  reschedule never destroys the original ask
--   source, utm_*, landing_page,
--   referrer                       cookie-free attribution, read from the URL
--   updated_at, confirmed_at,
--   completed_at, cancelled_at     status timeline
--   reminder_sent_at,
--   review_request_sent_at         idempotency guards — a scheduled job MUST
--                                  check these or a retry mails twice
--   quoted_price                   set at confirmation, for revenue reporting
--
-- The attribution fields arrive from a URL and are attacker-controlled, so
-- booking_requests_attrib_len bounds every one of them.
--
-- ---------------------------------------------------------------------------
-- status vocabulary
-- ---------------------------------------------------------------------------
-- new|confirmed|declined|done  ->  pending|confirmed|completed|cancelled|no_show
--
-- Both sets remain valid in the CHECK constraint. The deployed site never
-- writes status (it relies on the default), so widening first and mapping
-- second meant nothing could fail mid-deploy. Existing rows were renamed in
-- place: new->pending, done->completed, declined->cancelled. No row was
-- deleted and no row changed meaning. Default is now 'pending'.
--
-- booking_requests_touch keeps updated_at correct without the application
-- having to remember.
--
-- ---------------------------------------------------------------------------
-- appointments view
-- ---------------------------------------------------------------------------
-- WITH (security_invoker = true) is load-bearing. Without it the view runs
-- with the definer's rights and would hand anon every customer's name and
-- phone through PostgREST, defeating the RLS on the table underneath. With
-- it, the view inherits the table's policies exactly.
--
-- Verify after any change to this view:
--   curl "$SUPABASE_URL/rest/v1/appointments?select=customer_name,phone" \
--        -H "apikey: <publishable key>"
--   -> must return []


-- ===========================================================================
-- Phase 4 — admin access, status workflow, confirmation email
-- APPLIED 2026-08-26
-- ===========================================================================
--
--   phase4_admin_access
--   phase4_status_email_trigger
--   phase4_is_admin_security_invoker
--
-- ---------------------------------------------------------------------------
-- Who may read bookings
-- ---------------------------------------------------------------------------
-- THE TRAP: the obvious policy is `to authenticated`, which reads as
-- "signed-in staff". It is not. `authenticated` is ANY account in the
-- project, so with open sign-ups a stranger could register and read every
-- customer's name, phone and notes. Access is granted to an explicit
-- allowlist instead — public.admins, tested by public.is_admin().
--
-- is_admin() is SECURITY INVOKER, not DEFINER. PostgREST exposes every public
-- function at /rest/v1/rpc/<name>, and a definer-rights function there is a
-- lever waiting to be found. It does not need the rights: the policy on
-- public.admins already lets a user read their own row, so invoker rights
-- return the same answer.
--
-- There is deliberately NO delete policy on booking_requests. A cancelled
-- appointment is a status, not an absence — deleting it would destroy the
-- attribution history the ad-spend report depends on.
--
-- ---------------------------------------------------------------------------
-- Status changes and the confirmation email
-- ---------------------------------------------------------------------------
-- on_booking_status_change() is BEFORE UPDATE, because it assigns to NEW.
-- An AFTER trigger's assignments are discarded and confirmed_at would
-- silently never be set.
--
-- Guarded on `status IS DISTINCT FROM old.status` so it fires on the
-- transition, not on every save. Without that, correcting a phone number on
-- an already-confirmed booking would email the client a second confirmation.
--
-- Living in the database rather than the dashboard means the email sends
-- however the status changed — admin page, Supabase Studio, or a future
-- automation. There is no path that confirms an appointment silently.
--
-- ---------------------------------------------------------------------------
-- ONE MANUAL STEP
-- ---------------------------------------------------------------------------
-- Supabase has no SQL-safe way to create an auth user (passwords are hashed
-- by the Auth service, not by us). So:
--
--   1. Dashboard -> Authentication -> Users -> Add user
--      Email: mirabellekamga4@gmail.com, set a password, auto-confirm.
--   2. Dashboard -> Authentication -> Providers -> Email
--      TURN OFF "Enable sign-ups". Without this anyone can create an
--      account. They would still not be an admin, but there is no reason to
--      let strangers hold accounts on this project at all.
--   3. Then run, with the new user's id:
--
--        insert into public.admins (user_id, email)
--        select id, email from auth.users
--        where email = 'mirabellekamga4@gmail.com'
--        on conflict (user_id) do nothing;
--
-- Verify afterwards: sign in at /admin.html and confirm the pending queue
-- lists real bookings. If it is empty but bookings exist, the admins row is
-- missing.


-- ===========================================================================
-- Phase 5 — reminders and review requests
-- APPLIED 2026-08-26
-- ===========================================================================
--
--   phase5_settings
--   phase5_scheduled_jobs      (+ Edge Function send-scheduled)
--
-- Two pg_cron jobs, both daily, times in UTC:
--   mirabelle-reminders  0 14 * * *   24h-before reminder
--   mirabelle-reviews   15 14 * * *   review request, 24-48h after completion
--
-- 14:00 UTC is 10am Eastern in summer and 9am in winter - a civil hour to
-- receive either message in both.
--
-- ---------------------------------------------------------------------------
-- Why selection is in SQL and rendering is in the function
-- ---------------------------------------------------------------------------
-- The sent-at column is stamped in the SAME statement that queues the send.
-- The guard and the send therefore cannot drift apart, which is the usual way
-- a reminder system starts mailing people twice.
--
-- The consequence, deliberately chosen: if Resend later rejects the mail, the
-- row is already stamped and will NOT retry. One client misses one email,
-- which is recoverable by hand. The alternative - stamp after a confirmed
-- send - re-sends on every tick if the process dies in between, and a client
-- receiving the same reminder five times is the failure people actually
-- notice. To re-send one deliberately, null the column.
--
-- `for update skip locked` so two overlapping runs cannot claim the same row.
--
-- ---------------------------------------------------------------------------
-- Tomorrow, in whose timezone
-- ---------------------------------------------------------------------------
-- Reminders compare against (now() at time zone 'America/New_York')::date + 1,
-- not a UTC date. With UTC, an evening appointment would be reminded a day
-- early for part of the year.
--
-- ---------------------------------------------------------------------------
-- The review URL
-- ---------------------------------------------------------------------------
-- Held in public.settings, not in code, so it can be set without a deploy.
-- While it is null send_review_requests() returns 0 and sends NOTHING: an
-- email asking for a review that leads nowhere spends goodwill and earns no
-- review. To switch it on:
--
--   update public.settings
--   set value = 'https://g.page/r/YOUR_ID/review'
--   where key = 'google_review_url';
--
-- completed_at also has a 14-day upper bound, so switching the URL on later
-- cannot mail every client the salon has ever served, all at once.
--
-- ---------------------------------------------------------------------------
-- Verified on apply
-- ---------------------------------------------------------------------------
--   review job with no URL           -> 0 sent
--   one confirmed appointment due    -> 1 sent, HTTP 200 "ok"
--   second and third run             -> 0 sent (already stamped)
--   same row set to cancelled        -> 0 sent
--   total outbound calls in the test -> exactly 2, none of them duplicates
